const SET_DESTINATION = "SET_DESTINATION";
const SET_PICKUP = "SET_PICKUP";
const SET_PICKUP_TIME = "SET_PICKUP_TIME";
const SET_USER = "SET_USER";
const EXPAND_SET_PICKUP = "EXPAND_SET_PICKUP";
const COLLAPSE_SET_PICKUP = "COLLAPSE_SET_PICKUP";
const SET_SCHOOL = "SET_SCHOOL";

module.exports = {
  SET_DESTINATION,
  SET_PICKUP,
  SET_PICKUP_TIME,
  SET_USER,
  EXPAND_SET_PICKUP,
  COLLAPSE_SET_PICKUP,
  SET_SCHOOL
};
